site_name: DataFun 07 Regression
site_url: https://justicetefera.github.io/datafun-07-regression/

theme:
  name: material
  palette:
    primary: blue
    accent: red

nav:
  - Home: index.md
  - Project Instructions: project-instructions.md
  - Your Files: your-files.md
  - Glossary: glossary.md
  - API: api.md
